"""Resolve the package version, without ever reading pyproject.toml at runtime.

Two sources, in order:

1. ``cpumon._version``, generated by ``tools/build_zipapp.py`` and present only
   inside a built artifact. It wins because an archive carries no installed
   distribution metadata, and because the version it was built from is the one
   that artifact really is.
2. The installed distribution metadata (``*.dist-info/METADATA``), which is how
   a ``poetry install`` checkout resolves it. Written at install time, so a
   version bump shows up after the next install.

Both are generated out of ``[project].version``, which stays the single source
of truth. Do not add a pyproject.toml fallback here: the file is not shipped
with the app.
"""

from __future__ import annotations

from importlib import import_module
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version

_DISTRIBUTION_NAME = "cpumon"  # must match [project].name in pyproject.toml
_BAKED_MODULE = "cpumon._version"
_UNKNOWN_VERSION = "0.0.0"


def _read_baked_version() -> str | None:
    """The build-time version, or None outside a built artifact.

    Imported dynamically on purpose: the module is absent from the source tree
    by design, so a static import would be an unresolvable name everywhere but
    inside the archive.
    """
    try:
        module = import_module(_BAKED_MODULE)
    except ImportError:
        return None
    return str(getattr(module, "__version__", "")) or None


def _read_version() -> str:
    baked = _read_baked_version()
    if baked is not None:
        return baked
    try:
        return _pkg_version(_DISTRIBUTION_NAME)
    except PackageNotFoundError:
        return _UNKNOWN_VERSION


__version__: str = _read_version()
